# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZ2l9m1GeAYo2bacGuQRKqu1miL48ci_
"""

import pandas as pd
import torch
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from transformers import BertTokenizer
from transformers import BertForSequenceClassification
from transformers import Trainer
from transformers import TrainingArguments
from transformers import AutoModelForSequenceClassification

from datasets import load_dataset

# 1. Load the dataset
dataset = load_dataset("SetFit/sst5")

# 2. Define the mapping function
def map_to_custom_labels(example):
    original_label = example['label']
    if original_label in [3, 4]:
        example['custom_label'] = 0  # Positive
    elif original_label in [0, 1]:
        example['custom_label'] = 1  # Negative
    else:
        example['custom_label'] = 2  # Neutral
    return example

# 3. Apply the mapping and clean up columns
mapped_dataset = dataset.map(map_to_custom_labels)
mapped_dataset = mapped_dataset.remove_columns(["label", "label_text"]) # Removed "text_id" and added "label_text"
mapped_dataset = mapped_dataset.rename_column("custom_label", "label")

# 4. Shuffle and select exactly 5,000 examples from the training split
# Using a fixed seed (like 42) ensures you get the same 5,000 rows every time you run the script
small_train_dataset = mapped_dataset['train'].shuffle(seed=42).select(range(1500))

print(f"Training set size: {len(small_train_dataset)}")
print(small_train_dataset[0])

small_train_dataset

display(small_train_dataset)

import pandas as pd

# Convert the small_train_dataset to a pandas DataFrame to view its contents
small_train_df = pd.DataFrame(small_train_dataset)

# Display the first few rows of the DataFrame
display(small_train_df.head(10))

# Prepare the data for the model from the new dataset
texts = list(small_train_df["text"])
labels = list(small_train_df["label"])
print(f"Total texts count: {len(texts)}")
print(f"Total labels count: {len(labels)}")

type(texts)

train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts,
    labels,
    test_size=0.2,
    random_state=42
)

# -----------------------------
# Load tokenizer
# -----------------------------

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)

# -----------------------------
# Dataset class
# -----------------------------

class ReviewDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):
        return len(self.labels)


train_dataset = ReviewDataset(train_encodings, train_labels)
test_dataset = ReviewDataset(test_encodings, test_labels)

# -----------------------------
# Train or load model
# -----------------------------

if not os.path.exists("sentiment_model"):

    model = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased",
        num_labels=3
    )

    training_args = TrainingArguments(
        output_dir="./results",
        num_train_epochs=3,
        per_device_train_batch_size=4
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset
    )

    trainer.train()

    trainer.save_model("sentiment_model")
    tokenizer.save_pretrained("sentiment_model")

else:

    model = AutoModelForSequenceClassification.from_pretrained("sentiment_model")

    trainer = Trainer(model=model)

# -----------------------------
# Evaluate model
# -----------------------------

predictions = trainer.predict(test_dataset)

preds = predictions.predictions.argmax(axis=1)
true_labels = predictions.label_ids

precision, recall, f1, _ = precision_recall_fscore_support(
    true_labels,
    preds,
    average="weighted"
)

accuracy = accuracy_score(true_labels, preds)

loss = predictions.metrics["test_loss"]

print("\nModel Evaluation Metrics:")
print("Loss:", loss)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# -----------------------------
# Predict sentiment
# -----------------------------

sentiment_labels = ["positive", "negative", "neutral"]

model.eval()

review = input("\nEnter movie review: ")

inputs = tokenizer(
    review,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=128
)

outputs = model(**inputs)

prediction = torch.argmax(outputs.logits, dim=1).item()

print("Sentiment:", sentiment_labels[prediction])