# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16z9WMp7GGeaQfvbEt5JWKKvdv3-I9V2T
"""

import pandas as pd
import torch
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from transformers import BertTokenizer
from transformers import BertForSequenceClassification
from transformers import Trainer
from transformers import TrainingArguments
from transformers import AutoModelForSequenceClassification


# -----------------------------
# Load dataset
# -----------------------------

data = pd.read_csv("reviews_large.csv")

texts = list(data["review"])
labels = list(data["sentiment"])


# -----------------------------
# Convert labels to numbers
# -----------------------------

label_map = {
    "negative": 0,
    "neutral": 1,
    "positive": 2
}

labels = [label_map[l] for l in labels]


# -----------------------------
# Train/Test Split
# -----------------------------

train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts,
    labels,
    test_size=0.2,
    random_state=42
)


# -----------------------------
# Load tokenizer
# -----------------------------

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)


# -----------------------------
# Dataset class
# -----------------------------

class ReviewDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):
        return len(self.labels)


train_dataset = ReviewDataset(train_encodings, train_labels)
test_dataset = ReviewDataset(test_encodings, test_labels)


# -----------------------------
# Train or load model
# -----------------------------

if not os.path.exists("sentiment_model"):

    model = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased",
        num_labels=3
    )

    training_args = TrainingArguments(
        output_dir="./results",
        num_train_epochs=3,
        per_device_train_batch_size=4
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset
    )

    trainer.train()

    trainer.save_model("sentiment_model")
    tokenizer.save_pretrained("sentiment_model")

else:

    model = AutoModelForSequenceClassification.from_pretrained("sentiment_model")

    trainer = Trainer(model=model)


# -----------------------------
# Evaluate model
# -----------------------------

predictions = trainer.predict(test_dataset)

preds = predictions.predictions.argmax(axis=1)
true_labels = predictions.label_ids

precision, recall, f1, _ = precision_recall_fscore_support(
    true_labels,
    preds,
    average="weighted"
)

accuracy = accuracy_score(true_labels, preds)

loss = predictions.metrics["test_loss"]

print("\nModel Evaluation Metrics:")
print("Loss:", loss)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


# -----------------------------
# Predict sentiment
# -----------------------------

sentiment_labels = ["negative", "neutral", "positive"]

model.eval()

review = input("\nEnter movie review: ")

inputs = tokenizer(
    review,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=128
)

outputs = model(**inputs)

prediction = torch.argmax(outputs.logits, dim=1).item()

print("Sentiment:", sentiment_labels[prediction])